### ISSUE TITLE
Would you consider supporting the use of the `sass` package?

### ISSUE THREAD

**Issue by BiosSun** [rlamana/docusaurus-plugin-sass#10]
For example, instead of set the dependency on `node-sass` in this package, let users set and install it themselves:

```bash
yarn add docusaurus-plugin-sass sass
```

**Comment by roydukkey** [comment]
Yes! Please use `optionalDependencies` or `peerDependencies` for the sass compiler.

**Comment by roydukkey** [comment]
Allow `sass-loader` to manage Sass compiler dependency. It lists `node-sass` and `sass` as `peerDependencies` with `peerDependenciesMeta` [configuring both packages](https://github.com/webpack-contrib/sass-loader/blob/1329538acf40023b0f13313fef716063ca665b89/package.json#L41-L57) to optional.

**Comment by slorber** [comment]
Seems to make sense

The webpack doc seems to recommend using dart sass
https://webpack.js.org/loaders/sass-loader/

LibSass/Node sass seems deprecated: https://sass-lang.com/blog/libsass-is-deprecated

**Comment by BiosSun** [comment]
#11

**Comment by BiosSun** [comment]
Yes, for now, compared to Dart Sass, LibSass has not many advantages.
