### ISSUE TITLE
Use inside other plugins?

### ISSUE THREAD

**Issue by rohit-gohri** [rlamana/docusaurus-plugin-sass#13]
I had made a plugin for docusaurus, https://github.com/rohit-gohri/redocusaurus, and I wanted to use sass files for my theme components. Is there a way I could use this plugin inside my plugin so that people don't have to install it separately?

And would it be a problem if people also have this installed separately?

**Comment by rlamana** [comment]
As long as it is listed in the `dependencies` of the `package.json` of your plugin it will be automatically installed for those using your plugin. 
If you don't want it to be install but warn people to install it use the `peerDependencies` property instead.
