### ISSUE TITLE
Plugin won't install in gitlab CI

### ISSUE THREAD

**Issue by guillaume-ion** [rlamana/docusaurus-plugin-sass#14]
I've recently added this plugin to my docusaurus website. However when deploying to gitLab the `yarn install` job fails everytime with : 

`[4/4] Building fresh packages...
error /builds/ion-energy/edison-kb-private/node_modules/node-sass: Command failed.`

Thank you !

**Comment by guillaume-ion** [comment]
Never mind I forgot to add the plugin to my production configu

**Comment by rlamana** [comment]
This should be fix with the latest release (0.1.14, PR: #11)
