### ISSUE TITLE
Problem with dependency tree with npm 7

### ISSUE THREAD

**Issue by seblejeune** [rlamana/docusaurus-plugin-sass#19]
Hi,

I use npm 7, docusaurus 2.0.0-beta and your docusaurus-plugin-sass.

I have a problem with the peer dependencies. Actually you set "@docusaurus/core": "^2.0.0" but npm 7 does not install pre-release dependencies with a '^'.

This possible for you to change and put >2.0.0-beta by example ?

As long as the release version of docusaurus hasn't officially been released.

This my stack trace when I install your plugin : 

```js
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend-documentation@0.0.0
npm ERR! Found: @docusaurus/core@2.0.0-beta.ff31de0ff
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"^2.0.0-beta.ff31de0ff" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @docusaurus/core@"^2.0.0" from docusaurus-plugin-sass@0.2.1
npm ERR! node_modules/docusaurus-plugin-sass
npm ERR!   docusaurus-plugin-sass@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/lejes/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lejes/.npm/_logs/2021-07-12T15_37_39_084Z-debug.log
```

node version : v14.17.2
npm version : 7.19.1

Thanks

**Comment by TranXuanHoang** [comment]
I got the same installation error when upgrading the version of Docusaurus. It would be great if we could fix the bug.

```shell
npm install --save docusaurus-plugin-sass sass 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: zdocs-new@0.0.0
npm ERR! Found: @docusaurus/core@2.0.0-beta.6
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"2.0.0-beta.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @docusaurus/core@"^2.0.0" from docusaurus-plugin-sass@0.2.1
npm ERR! node_modules/docusaurus-plugin-sass
npm ERR!   docusaurus-plugin-sass@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
@docusaurus/core: 2.0.0-beta.6
node version : v16.8.0
npm version : 7.21.0

Thanks!

**Comment by JohannesZahn** [comment]
I have the same issue. With docusaurus version 2.0.0-beta.3 everything works fine but we'd like to upgrade to beta.6

**Comment by cstipkovic** [comment]
I got the same issue here.
I did test with @docusaurus/core@"2.0.0" and @docusaurus/core@"2.0.0-beta.6", and the dependency problem is the same.

**Comment by cstipkovic** [comment]
I made another test and if I try using **yarn**, the problem of dependency not happens, but I need to install **sass module** before run **yarn/npm start**, because it's not installing the **peerDependency** for **sass-1.30.0**.

If I add sass module after run **yarn install**, it runs and load right.

**Comment by JanCizmar** [comment]
+1

**Comment by homotechsual** [comment]
For now you can get this to install using `npm install --save docusaurus-plugin-sass sass --legacy-peer-deps`
