### ISSUE TITLE
Add types to support imports

### ISSUE THREAD

**Issue by roydukkey** [rlamana/docusaurus-plugin-sass#20]
Like is done for [`@docusaurus/module-type-aliases`](https://github.com/facebook/docusaurus/blob/7f7b858cd4f5f5c26b4559d6f5661d0c8ace1737/packages/docusaurus-module-type-aliases/src/index.d.ts#L269-L277) and [`react-scripts`](https://github.com/facebook/create-react-app/blob/1465357b842eae16b2b52243d2e55db9a17f0425/packages/react-scripts/lib/react-app.d.ts#L63-L71). This enables IDE helpers.

I believe there are four in total:

```ts
declare module '*.module.scss' {
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module '*.module.sass' {
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module '*.scss' {
  const src: string;
  export default src;
}

declare module '*.sass' {
  const src: string;
  export default src;
}
```

**Comment by nick-inkeep** [comment]
@rlamana , can the pull request that fixes this be merged?
