### ISSUE TITLE
Maintained? Website down...

### ISSUE THREAD

**Issue by homotechsual** [rlamana/docusaurus-plugin-sass#28]
Is this still maintained? The website appears to have gone offline with Vercel?

**Comment by rlamana** [comment]
This repository doesn't have a anything on vercel. In fact it doesn't have a website at all.

**Comment by peabnuts123** [comment]
@rlamana Huh? There is a link to a vercel website on the repository's front page.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/2322840/220470490-06c545a0-eff0-424d-ac9d-023e4fbee127.png">

**Comment by homotechsual** [comment]
What @peabnuts123 says.

**Comment by rlamana** [comment]
Sorry, that was just a test, I just removed the link to avoid confusion.
