### ISSUE TITLE
Is there a convention to target documentation styles only?

### ISSUE THREAD

**Issue by viztastic** [rlamana/docusaurus-plugin-sass#3]
Does this module require a specific pattern to target documentation only h1,h2,h3 etc.. ?

When I inspect docusaurus 2 titles it seems to carry interesting class names along the lines of `docTitle_node_modules-@docusaurus-theme-classic-src-theme-DocItem-`, is it best practice to target these specifically using this sass module or should I approach it differently?

I am trying to avoid creating a global h1, h2, h3 style so I can have a different look on my documentation pages compared to the rest of the website.

PS: Great module, thanks for this!

**Comment by rlamana** [comment]
I think you are trying to style a theme component, for that you will have to "swizzle" the component. Please, read docusaurus 2 official documentation for that: https://v2.docusaurus.io/docs/using-themes#swizzling-theme-components.

This plugin should work to use sass/scss when styling your "swizzled" component. I hope this helps.
