### ISSUE TITLE
Support for Docusaurus V3

### ISSUE THREAD

**Issue by nick-inkeep** [rlamana/docusaurus-plugin-sass#32]
Would be great to understand what's needed to support Docusaurus V3, which recently came out in alpha. Getting the following peer dep warning:

warning " > docusaurus-plugin-sass@0.2.4" has incorrect peer dependency "@docusaurus/core@^2.0.0-beta".

**Comment by noomorph** [comment]
@nick-inkeep, just in case you're hurrying, I released a temporary fork: <https://www.npmjs.com/package/@noomorph/docusaurus-plugin-sass>

The pull request is on its way (#33). I hope @rlamana takes a minute to review and merge it soon.

**Comment by rlamana** [comment]
The PR has been approved and merged. Thanks for the contribution!

**Comment by noomorph** [comment]
@rlamana, thanks for helping the early adopters of V3.
