### ISSUE TITLE
README.md setup instructions

### ISSUE THREAD

**Issue by TimKrauseDev** [rlamana/docusaurus-plugin-sass#34]
**Issue**
---
I followed the README instructions to set up SCSS in my Docusaurus 3 repo. 

When updating the module style name from `styles.module.css` to `styles.module.scss`, the import statements inside of the `index.tsx` files throw a false error (the styles still work) of `Cannot find module './styles.module.scss' or its corresponding type declarations.`

**Proposed Solution**
---
Add instructions to the README to include setting up the type declarations file: `typings.d.ts`

```ts
declare module "*.module.scss"
```

**Comment by rlamana** [comment]
Typescript support is already explained in the README file here: https://github.com/rlamana/docusaurus-plugin-sass?tab=readme-ov-file#typescript-support. There is no need to add that declarations as it is already defined here: https://github.com/rlamana/docusaurus-plugin-sass/blob/master/docusaurus-plugin-sass.d.ts. I think there must be some misconfiguration in your project. Please, let me know if you can make it work with the default typing declaration and removing your changes in your `typings.d.ts` file.
