### ISSUE TITLE
Invalid Options in Docusaurus Alpha 62

### ISSUE THREAD

**Issue by atomicpages** [rlamana/docusaurus-plugin-sass#6]
Not sure if this is an anomaly or if its here to stay, but docusaurus alpha.62 is passing an `id` to `options` 

https://github.com/rlamana/docusaurus-plugin-sass/blob/a0f174995c50b1a3400af4c4c209e138e2ace711/docusaurus-plugin-sass.js#L1

```
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'id'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
```

Happy to send a PR, but I guess it might be better to wait and see?

**Comment by atomicpages** [comment]
Oh, looks like PR #5 fixes this 😄

**Comment by slorber** [comment]
can be closed @rlamana :)
